name: Scrape and Save Hourly

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas matplotlib
    
    - name: Scrape and save data
      run: python main.py

    - name: Generate HTML card with graph
      run: python generate_html_card.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.csv html_card.html
        git commit -m "Update data and HTML card" || echo "No changes to commit"
        git push
