name: Docker Build and Run

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jacobedurham/priceoftea-python:latest

      - name: Pull and run Docker container
        run: |
          docker pull jacobedurham/priceoftea-python:latest
          docker run --rm jacobedurham/priceoftea-python:latest
