name: Fetch Titanium Stock Price and Generate Chart

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  fetch_titanium_price:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main.py
      run: |
        export ALPHAVANTAGE_API_KEY=4TRT8KNTAO3IEB5H
        python main.py
