name: Scrape, Save, and Generate Graph Hourly

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas matplotlib imgkit

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf
        
    - name: Scrape and save data
      run: python main.py
    
    - name: Generate graph
      run: python generate_graph.py

    - name: Generate HTML card
      run: python generate_html_card.py
